### ISSUE TITLE
Change mail directive prefix from MD_ to SMTP_

### ISSUE THREAD

**Issue by shon** [stckme/apphelpers#71]
All SMTP config variables are prefixed as MD_ like below
```
MD_HOST = "localhost"                                                           
MD_PORT = 10000                                                                 
MD_USERNAME = None                                                              
MD_KEY = None        
```
Reason is that we started Mandrill service for sending SMTP emails. 
It's time to rename these directives to something generic. I propose SMTP_.

**Comment by sayanarijit** [comment]
PR: https://github.com/stckme/apphelpers/pull/73

**Comment by sayanarijit** [comment]
Done in https://github.com/stckme/apphelpers/pull/73
